import { ChevronDown } from '@/components/common/Icons/ChevronDown';
import MultiSelectListBox from '@/components/common/MultiSelectListBox';
import SelectionGroup from '@/components/common/SelectionGroup';
import Head from 'next/head';
import { useState } from 'react';
//import { Inter } from '@next/font/google';
import DropdownMenu from '../components/common/DropdownMenu';

//const inter = Inter({ subsets: ['latin'] });
export default function Home() {
  const [selected, setSelected] = useState<string | undefined>(undefined);
  const [interval, setInterval] = useState<number | undefined>(1);
  const [states, setStates] = useState<number[]>([1]);

  function handleDropdownOnClick(item: string) {
    setSelected(item);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main>
        <h1 className="text-black">Hello World!</h1>

        <div className="w-full flex gap-8 px-2">
          <DropdownMenu
            buttonLabel="Attribute"
            menuItems={['Daily', 'Blood A']}
            handleOnClick={handleDropdownOnClick}
            buttonIcon={<ChevronDown size="sm" />}
            selectedItem={selected}
          />

          <SelectionGroup
            options={[
              { id: 1, label: 'Daily' },
              { id: 2, label: 'Monthly' },
              { id: 3, label: 'Yearly' },
            ]}
            handleOnChange={setInterval}
            value={interval}
          />

          <MultiSelectListBox
            buttonLabel="States"
            options={[
              { id: 1, label: 'Kuala Lumpur' },
              { id: 2, label: 'Melaka' },
              { id: 3, label: 'Johor' },
              { id: 4, label: 'Sarawak' },
            ]}
            handleOnChange={setStates}
            value={states}
            optionWithIcon={false}
          />
        </div>
      </main>
    </>
  );
}
