import Head from 'next/head';
//import { Inter } from '@next/font/google';
import DropdownMenu from '@/components/common/DropdownMenu';

//const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main>
        <h1 className="text-black">Hello World! testing</h1>
        <DropdownMenu
          buttonLabel="Attribute"
          menuItems={['Daily', 'Blood A']}
          handleItemOnClick={() => console.log('item clicked.')}
        />
      </main>
    </>
  );
}
