name: Deploy client to S3

on:
  push:
    branches:
      - main
    path:
      - client/**

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client/

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Create env file
        run: echo "${{ secrets.CLIENT_ENV_FILE }}" > .env

      - name: Run build
        run: npm run build

      - name: Install Plugin and Deploy
        uses: serverless/github-action@v3.1
        with:
          args: -c "serverless plugin install --name serverless-s3-sync && serverless deploy"
          entrypoint: /bin/sh
        env:
          # SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          # or if using AWS credentials directly
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
